# fly.toml app configuration file for Bhashini QoS Full Stack Monitoring System
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "bhashini-qos-dashboards"
primary_region = "bom"  # Mumbai region for better India performance

[build]
  dockerfile = "Dockerfile.full-stack"

[env]
  DOCKER_INFLUXDB_INIT_USERNAME = "admin"
  DOCKER_INFLUXDB_INIT_PASSWORD = "admin123"
  DOCKER_INFLUXDB_INIT_ORG = "bhashini"
  DOCKER_INFLUXDB_INIT_BUCKET = "qos_metrics"
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN = "admin-token-123"
  GF_SECURITY_ADMIN_USER = "admin"
  GF_SECURITY_ADMIN_PASSWORD = "admin123"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "30s"
  interval = "30s"
  method = "GET"
  timeout = "10s"
  path = "/api/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048

[deploy]
  release_command = "echo 'Full Stack Deployment Complete'"
