apiVersion: 1

datasources:
  - name: InfluxDB-Customer-enterprise_1
    uid: InfluxDB-Customer-enterprise_1
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: ${INFLUXDB_ENTERPRISE_1_TOKEN}
    jsonData:
      version: Flux
      organization: ${INFLUXDB_ORG}
      defaultBucket: ${INFLUXDB_BUCKET}
      tlsSkipVerify: true
      httpMethod: POST
      queryTimeout: 60s
      maxSeries: 10000
      defaultQuery: |
        // Customer tenant-isolated query template for enterprise_1
        // Automatically filters by tenant_id for complete data isolation
        from(bucket: "${INFLUXDB_BUCKET}")
          |> range(start: -1h)
          |> filter(fn: (r) => r["_measurement"] == "qos_metrics")
          |> filter(fn: (r) => r["tenant_id"] == "enterprise_1")
          |> group(columns: ["service_name", "metric_type"])
          |> mean()
          |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
    editable: false
    isDefault: false

  - name: InfluxDB-Customer-startup_2
    uid: InfluxDB-Customer-startup_2
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: ${INFLUXDB_STARTUP_2_TOKEN}
    jsonData:
      version: Flux
      organization: ${INFLUXDB_ORG}
      defaultBucket: ${INFLUXDB_BUCKET}
      tlsSkipVerify: true
      httpMethod: POST
      queryTimeout: 60s
      maxSeries: 10000
      defaultQuery: |
        // Customer tenant-isolated query template for startup_2
        // Automatically filters by tenant_id for complete data isolation
        from(bucket: "${INFLUXDB_BUCKET}")
          |> range(start: -1h)
          |> filter(fn: (r) => r["_measurement"] == "qos_metrics")
          |> filter(fn: (r) => r["tenant_id"] == "startup_2")
          |> group(columns: ["service_name", "metric_type"])
          |> mean()
          |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
    editable: false
    isDefault: false

  - name: InfluxDB-Customer-freemium_1
    uid: InfluxDB-Customer-freemium_1
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: ${INFLUXDB_FREEMIUM_1_TOKEN}
    jsonData:
      version: Flux
      organization: ${INFLUXDB_ORG}
      defaultBucket: ${INFLUXDB_BUCKET}
      tlsSkipVerify: true
      httpMethod: POST
      queryTimeout: 60s
      maxSeries: 10000
      defaultQuery: |
        // Customer tenant-isolated query template for freemium_1
        // Automatically filters by tenant_id for complete data isolation
        from(bucket: "${INFLUXDB_BUCKET}")
          |> range(start: -1h)
          |> filter(fn: (r) => r["_measurement"] == "qos_metrics")
          |> filter(fn: (r) => r["tenant_id"] == "freemium_1")
          |> group(columns: ["service_name", "metric_type"])
          |> mean()
          |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
    editable: false
    isDefault: false
