apiVersion: 1
muteTimes:
  - name: maintenance-window
    time_intervals:
      - times:
          - start_time: "02:00"
            end_time: "04:00"
        weekdays: ["monday","tuesday","wednesday","thursday","friday"]
